import { TranslationKeys } from '../../react-i18next';

export type CreditMember = {
  name: TranslationKeys;
  position: TranslationKeys;
};

export type CreditTeam = {
  title: TranslationKeys;
  members: CreditMember[];
};

// Members
export const CREDITS_CULTURE_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.CULTURE.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.CULTURE.MEMBER.01.POSITION',
  },
  {
    name: 'CREDITS.GROUP.CULTURE.MEMBER.02.NAME',
    position: 'CREDITS.GROUP.CULTURE.MEMBER.02.POSITION',
  },
  {
    name: 'CREDITS.GROUP.CULTURE.MEMBER.03.NAME',
    position: 'CREDITS.GROUP.CULTURE.MEMBER.03.POSITION',
  },
];

export const CREDITS_DRAWING_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.DRAWING.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.DRAWING.MEMBER.01.POSITION',
  },
];

export const CREDITS_IT_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.IT.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.IT.MEMBER.01.POSITION',
  },
  {
    name: 'CREDITS.GROUP.IT.MEMBER.02.NAME',
    position: 'CREDITS.GROUP.IT.MEMBER.02.POSITION',
  },
];

export const CREDITS_MENTOR_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.MENTOR.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.MENTOR.MEMBER.01.POSITION',
  },
];

export const CREDITS_MMH_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.MMH.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.MMH.MEMBER.01.POSITION',
  },
  {
    name: 'CREDITS.GROUP.MMH.MEMBER.02.NAME',
    position: 'CREDITS.GROUP.MMH.MEMBER.02.POSITION',
  },
  {
    name: 'CREDITS.GROUP.MMH.MEMBER.03.NAME',
    position: 'CREDITS.GROUP.MMH.MEMBER.03.POSITION',
  },
  {
    name: 'CREDITS.GROUP.MMH.MEMBER.04.NAME',
    position: 'CREDITS.GROUP.MMH.MEMBER.04.POSITION',
  },
];

export const CREDITS_SUPPORT_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.01.POSITION',
  },
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.02.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.02.POSITION',
  },
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.03.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.03.POSITION',
  },
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.04.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.04.POSITION',
  },
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.05.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.05.POSITION',
  },
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.06.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.06.POSITION',
  },
  {
    name: 'CREDITS.GROUP.SUPPORT.MEMBER.07.NAME',
    position: 'CREDITS.GROUP.SUPPORT.MEMBER.07.POSITION',
  },
];

export const CREDITS_TRANSLATOR_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.01.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.02.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.02.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.03.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.03.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.04.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.04.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.05.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.05.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.06.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.06.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.07.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.07.POSITION',
  },
  {
    name: 'CREDITS.GROUP.TRANSLATOR.MEMBER.08.NAME',
    position: 'CREDITS.GROUP.TRANSLATOR.MEMBER.08.POSITION',
  },
];

export const CREDITS_VETERINARIAN_MEMBERS: CreditMember[] = [
  {
    name: 'CREDITS.GROUP.VETERINARIAN.MEMBER.01.NAME',
    position: 'CREDITS.GROUP.VETERINARIAN.MEMBER.01.POSITION',
  },
  {
    name: 'CREDITS.GROUP.VETERINARIAN.MEMBER.02.NAME',
    position: 'CREDITS.GROUP.VETERINARIAN.MEMBER.02.POSITION',
  },
  {
    name: 'CREDITS.GROUP.VETERINARIAN.MEMBER.03.NAME',
    position: 'CREDITS.GROUP.VETERINARIAN.MEMBER.03.POSITION',
  },
  {
    name: 'CREDITS.GROUP.VETERINARIAN.MEMBER.04.NAME',
    position: 'CREDITS.GROUP.VETERINARIAN.MEMBER.04.POSITION',
  },
  {
    name: 'CREDITS.GROUP.VETERINARIAN.MEMBER.05.NAME',
    position: 'CREDITS.GROUP.VETERINARIAN.MEMBER.05.POSITION',
  },
  {
    name: 'CREDITS.GROUP.VETERINARIAN.MEMBER.06.NAME',
    position: 'CREDITS.GROUP.VETERINARIAN.MEMBER.06.POSITION',
  },
];

// Teams
export const CREDITS_TEAM_MENTOR: CreditTeam[] = [
  {
    title: 'CREDITS.GROUP.MENTOR.TITLE',
    members: CREDITS_MENTOR_MEMBERS,
  },
];

export const CREDITS_TEAM_MMH: CreditTeam[] = [
  {
    title: 'CREDITS.GROUP.MMH.TITLE',
    members: CREDITS_MMH_MEMBERS,
  },
];

export const CREDITS_TEAM_PROJECT: CreditTeam[] = [
  {
    title: 'CREDITS.GROUP.VETERINARIAN.TITLE',
    members: CREDITS_VETERINARIAN_MEMBERS,
  },
  {
    title: 'CREDITS.GROUP.TRANSLATOR.TITLE',
    members: CREDITS_TRANSLATOR_MEMBERS,
  },
  {
    title: 'CREDITS.GROUP.IT.TITLE',
    members: CREDITS_IT_MEMBERS,
  },
  {
    title: 'CREDITS.GROUP.SUPPORT.TITLE',
    members: CREDITS_SUPPORT_MEMBERS,
  },
  {
    title: 'CREDITS.GROUP.DRAWING.TITLE',
    members: CREDITS_DRAWING_MEMBERS,
  },
];
