# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
require 'dotenv'
Dotenv.load("./../.env.local")

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Setup Env (GitHub Actions)"
  lane :setup_env_github do
    setup_ci(
      force: true
    )
    match(type: "appstore", readonly: true)
  end
  
  desc "Load Certificates (local development)"
  lane :certificates do
    match(type: "appstore")
  end
  
  desc "Build App"
  lane :build do
    increment_version_number(
      version_number: File.read("../../../.VERSION"),
      xcodeproj: "App.xcodeproj"
    )
    increment_build_number(
      build_number: app_store_build_number(live: false) + 1,
      xcodeproj: "App.xcodeproj"
    )
    build_app(
      scheme: "App",
      workspace: "App.xcworkspace"
    )
  end

  desc "Build and Deploy App to Testflight"
  lane :beta do
    sync_code_signing(type: "appstore")
    build
    upload_to_testflight(
      changelog: File.read("../../../.NOTES")
    )
  end

  desc "Build and Deploy App to Store"
  lane :release do
    sync_code_signing(type: "appstore")
    build
    upload_to_app_store(
      changelog: File.read("../../../.NOTES")
    )
  end
end
