name: Screenshots
on: [push]
jobs:
  setup:
    name: Build App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Generate Optimized Images
        run: npm run generate:images
      - name: Build
        run: npm run build:ionic:browser
      - name: Generate Screenshots (en-US)
        env:
          JEST_PLAYWRIGHT_CONTEXT_OPTION_LOCAL: en-US
          JEST_PLAYWRIGHT_SCREENSHOT_SEARCH_QUERY: feed
        run: npm run generate:screenshots
      - name: Generate Screenshots (ta-IN)
        env:
          JEST_PLAYWRIGHT_CONTEXT_OPTION_LOCAL: ta-IN
          JEST_PLAYWRIGHT_SCREENSHOT_SEARCH_QUERY: உலர்ந்த
        run: npm run generate:screenshots
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: dist/screenshots
